name: CI Windows - Build Raylib Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer MinGW via Chocolatey
        run: choco install mingw -y

      - name: Ajouter MinGW au PATH
        shell: powershell
        run: |
          echo "C:\ProgramData\mingw64\mingw64\bin" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: Cloner et compiler Raylib
        shell: cmd
        run: |
          git clone https://github.com/raysan5/raylib.git
          cd raylib
          rmdir /s /q build
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" -DBUILD_EXAMPLES=OFF ..
          cmake --build .
          cmake --install . --prefix "C:/raylib"

      - name: Configurer le projet
        shell: cmd
        run: |
          cmake -B build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH="C:/raylib"

      - name: Compiler le projet
        shell: cmd
        run: cmake --build build --config Release

      - name: Vérifier si l'exécutable a été généré
        shell: powershell
        run: |
          if (Test-Path "build/raylib_project.exe") {
            Write-Output "Exécutable généré."
          } else {
            Write-Error "Pas d'exécutable"
            exit 1
          }
