name: CI Windows - Build Raylib Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer MinGW via Chocolatey
        run: choco install mingw -y

      - name: Ajouter MinGW au PATH
        shell: powershell
        run: |
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Télécharger Raylib précompilée
        run: |
          curl -L -o raylib.zip https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_mingw-w64.zip
          tar -xf raylib.zip
          move raylib-5.0_win64_mingw-w64 raylib

      - name: Configurer le projet avec CMake
        run: |
          cmake -B build -G "MinGW Makefiles" `
            -DCMAKE_PREFIX_PATH="${{ github.workspace }}/raylib" `
            -DCMAKE_BUILD_TYPE=Release

      - name: Compiler le projet
        run: cmake --build build --config Release

      - name: Vérifier la présence de l'exécutable
        run: |
          if (Test-Path "build/raylib_project.exe") {
            Write-Output "L'exécutable est présent."
          } else {
            Write-Error "L'exécutable est manquant."
            exit 1
          }
